# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: message-service-deployment
serviceName: message-service
appLabel: message-service
appName: message-service

replicaCount: 1

image:
  repository: kasiarakos/message-service
  tag: s14

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
rabbit_enabled: false
has_database: true
jdbc_url: jdbc:mysql://loans-db:3306/loan-db