# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: card-deployment
serviceName: card-service
appLabel: card-service
appName: card-service

replicaCount: 1

image:
  repository: kasiarakos/card-service
  tag: s14

containerPort: 9090

service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
rabbit_enabled: false
has_database: true
jdbc_url: jdbc:mysql://cards-db:3306/cards-db