# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-server-deployment
serviceName: gateway-server
appLabel: gateway-server
appName: gateway-server

replicaCount: 1

image:
  repository: kasiarakos/gateway-server
  tag: s14

containerPort: 10000

service:
  type: ClusterIP
  port: 10000
  targetPort: 10000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
rabbit_enabled: false
has_database: false