apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: kasiarakos/account-service:s13
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: ACCOUNT_SERVICE_APPLICATION_NAME
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: SPRING_PROFILE_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://accounts-db:3306/accounts-db"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbit"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
