apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service-deployment
  labels:
    app: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
        - name: card-service
          image: kasiarakos/card-service:s14
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: CARD_SERVICE_APPLICATION_NAME
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: SPRING_PROFILE_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: kasiarakos-config-map
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
