apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
  labels:
    app: accounts-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      containers:
        - name: accounts-db
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: accounts-db
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - name: http
              containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: loans-db
  labels:
    app: loans-db
spec:
  selector:
    app: loans-db
  type: LoadBalancer
  ports:
    - name: http
      port: 3307
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-db
  labels:
    app: loans-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans-db
  template:
    metadata:
      labels:
        app: loans-db
    spec:
      containers:
        - name: loans-db
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: loans-db
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - name: http
              containerPort: 3306

