apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.12-management
          env:
            - name: MYSQL_DATABASE
              value: rabbit
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - name: http
              containerPort: 15672
            - name: http1
              containerPort: 5672
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-external
  labels:
    app: rabbit
spec:
  selector:
    app: rabbit
  type: LoadBalancer
  ports:
    - name: http
      port: 15672
      targetPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-cluster
  labels:
    app: rabbit
spec:
  selector:
    app: rabbit
  type: ClusterIP
  ports:
    - name: http
      port: 5672
      targetPort: 5672