server:
  port: 9000
spring:
  application:
    name: card-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  datasource:
    url: jdbc:mysql://localhost:3308/cards-db
    username: root
    password: root

  jpa:
    show-sql: true

  sql:
    init:
      mode: always
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "card-service"
    description: "EazyBank Cards application"
    version: 1.0.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

